[build-system]
requires = ["setuptools>=45", "wheel", "pybind11>=2.12.0", "cmake>=3.10"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-vectordb"
version = "0.1.0"
description = "A simple vector database with HNSW indexing"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
keywords = ["vector", "database", "hnsw", "nearest-neighbor", "search"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "numpy>=1.19.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=3.0.0",
    "black>=22.0.0",
    "mypy>=0.950",
]

[project.urls]
Homepage = "https://github.com/plkumar/simple-vectordb-cpp"
Repository = "https://github.com/plkumar/simple-vectordb-cpp"
